# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.common import Common  # noqa: E501
from swagger_client.rest import ApiException


class TestCommon(unittest.TestCase):
    """Common unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommon(self):
        """Test Common"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.common.Common()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
