# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projectrun_api import ProjectrunApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectrunApi(unittest.TestCase):
    """ProjectrunApi unit test stubs"""

    def setUp(self):
        self.api = ProjectrunApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_all_project_runs(self):
        """Test case for read_all_project_runs

        Get all existing test runs for project  # noqa: E501
        """
        pass

    def test_read_project_run(self):
        """Test case for read_project_run

        Read project test run info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
