# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.container_top_ok_body import ContainerTopOKBody  # noqa: E501
from swagger_client.rest import ApiException


class TestContainerTopOKBody(unittest.TestCase):
    """ContainerTopOKBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerTopOKBody(self):
        """Test ContainerTopOKBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.container_top_ok_body.ContainerTopOKBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
