# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.file_api import FileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_file(self):
        """Test case for read_file

        Read file info.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
