# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projectresult_api import ProjectresultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectresultApi(unittest.TestCase):
    """ProjectresultApi unit test stubs"""

    def setUp(self):
        self.api = ProjectresultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_all_project_results(self):
        """Test case for read_all_project_results

        Read all project run results  # noqa: E501
        """
        pass

    def test_read_project_result(self):
        """Test case for read_project_result

        Read single project run result  # noqa: E501
        """
        pass

    def test_read_project_result_statistics(self):
        """Test case for read_project_result_statistics

        Read all project result statistics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
