# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.container_wait_ok_body_error import ContainerWaitOKBodyError  # noqa: E501
from swagger_client.rest import ApiException


class TestContainerWaitOKBodyError(unittest.TestCase):
    """ContainerWaitOKBodyError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContainerWaitOKBodyError(self):
        """Test ContainerWaitOKBodyError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.container_wait_ok_body_error.ContainerWaitOKBodyError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
