# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Account(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'avatar': 'str',
        'created': 'datetime',
        'email': 'str',
        'first_name': 'str',
        'id': 'int',
        'last_login': 'datetime',
        'last_name': 'str',
        'metadata': 'Metadata',
        'superuser': 'bool',
        'updated': 'datetime'
    }

    attribute_map = {
        'avatar': 'avatar',
        'created': 'created',
        'email': 'email',
        'first_name': 'first_name',
        'id': 'id',
        'last_login': 'last_login',
        'last_name': 'last_name',
        'metadata': 'metadata',
        'superuser': 'superuser',
        'updated': 'updated'
    }

    def __init__(self, avatar=None, created=None, email=None, first_name=None, id=None, last_login=None, last_name=None, metadata=None, superuser=None, updated=None):  # noqa: E501
        """Account - a model defined in Swagger"""  # noqa: E501
        self._avatar = None
        self._created = None
        self._email = None
        self._first_name = None
        self._id = None
        self._last_login = None
        self._last_name = None
        self._metadata = None
        self._superuser = None
        self._updated = None
        self.discriminator = None
        if avatar is not None:
            self.avatar = avatar
        if created is not None:
            self.created = created
        self.email = email
        self.first_name = first_name
        if id is not None:
            self.id = id
        if last_login is not None:
            self.last_login = last_login
        self.last_name = last_name
        if metadata is not None:
            self.metadata = metadata
        if superuser is not None:
            self.superuser = superuser
        if updated is not None:
            self.updated = updated

    @property
    def avatar(self):
        """Gets the avatar of this Account.  # noqa: E501


        :return: The avatar of this Account.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this Account.


        :param avatar: The avatar of this Account.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def created(self):
        """Gets the created of this Account.  # noqa: E501


        :return: The created of this Account.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Account.


        :param created: The created of this Account.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def email(self):
        """Gets the email of this Account.  # noqa: E501


        :return: The email of this Account.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Account.


        :param email: The email of this Account.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def first_name(self):
        """Gets the first_name of this Account.  # noqa: E501


        :return: The first_name of this Account.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Account.


        :param first_name: The first_name of this Account.  # noqa: E501
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def id(self):
        """Gets the id of this Account.  # noqa: E501


        :return: The id of this Account.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Account.


        :param id: The id of this Account.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def last_login(self):
        """Gets the last_login of this Account.  # noqa: E501


        :return: The last_login of this Account.  # noqa: E501
        :rtype: datetime
        """
        return self._last_login

    @last_login.setter
    def last_login(self, last_login):
        """Sets the last_login of this Account.


        :param last_login: The last_login of this Account.  # noqa: E501
        :type: datetime
        """

        self._last_login = last_login

    @property
    def last_name(self):
        """Gets the last_name of this Account.  # noqa: E501


        :return: The last_name of this Account.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Account.


        :param last_name: The last_name of this Account.  # noqa: E501
        :type: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def metadata(self):
        """Gets the metadata of this Account.  # noqa: E501


        :return: The metadata of this Account.  # noqa: E501
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this Account.


        :param metadata: The metadata of this Account.  # noqa: E501
        :type: Metadata
        """

        self._metadata = metadata

    @property
    def superuser(self):
        """Gets the superuser of this Account.  # noqa: E501


        :return: The superuser of this Account.  # noqa: E501
        :rtype: bool
        """
        return self._superuser

    @superuser.setter
    def superuser(self, superuser):
        """Sets the superuser of this Account.


        :param superuser: The superuser of this Account.  # noqa: E501
        :type: bool
        """

        self._superuser = superuser

    @property
    def updated(self):
        """Gets the updated of this Account.  # noqa: E501


        :return: The updated of this Account.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this Account.


        :param updated: The updated of this Account.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Account, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Account):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
