# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: v0.38.0
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssertPrecondition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'assert_id': 'int',
        'created': 'datetime',
        'expected': 'str',
        'id': 'int',
        'operator': 'str',
        '_property': 'str',
        'updated': 'datetime'
    }

    attribute_map = {
        'assert_id': 'assert_id',
        'created': 'created',
        'expected': 'expected',
        'id': 'id',
        'operator': 'operator',
        '_property': 'property',
        'updated': 'updated'
    }

    def __init__(self, assert_id=None, created=None, expected=None, id=None, operator=None, _property=None, updated=None):  # noqa: E501
        """AssertPrecondition - a model defined in Swagger"""  # noqa: E501
        self._assert_id = None
        self._created = None
        self._expected = None
        self._id = None
        self._operator = None
        self.__property = None
        self._updated = None
        self.discriminator = None
        if assert_id is not None:
            self.assert_id = assert_id
        if created is not None:
            self.created = created
        self.expected = expected
        if id is not None:
            self.id = id
        self.operator = operator
        self._property = _property
        if updated is not None:
            self.updated = updated

    @property
    def assert_id(self):
        """Gets the assert_id of this AssertPrecondition.  # noqa: E501


        :return: The assert_id of this AssertPrecondition.  # noqa: E501
        :rtype: int
        """
        return self._assert_id

    @assert_id.setter
    def assert_id(self, assert_id):
        """Sets the assert_id of this AssertPrecondition.


        :param assert_id: The assert_id of this AssertPrecondition.  # noqa: E501
        :type: int
        """

        self._assert_id = assert_id

    @property
    def created(self):
        """Gets the created of this AssertPrecondition.  # noqa: E501


        :return: The created of this AssertPrecondition.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this AssertPrecondition.


        :param created: The created of this AssertPrecondition.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def expected(self):
        """Gets the expected of this AssertPrecondition.  # noqa: E501


        :return: The expected of this AssertPrecondition.  # noqa: E501
        :rtype: str
        """
        return self._expected

    @expected.setter
    def expected(self, expected):
        """Sets the expected of this AssertPrecondition.


        :param expected: The expected of this AssertPrecondition.  # noqa: E501
        :type: str
        """
        if expected is None:
            raise ValueError("Invalid value for `expected`, must not be `None`")  # noqa: E501

        self._expected = expected

    @property
    def id(self):
        """Gets the id of this AssertPrecondition.  # noqa: E501


        :return: The id of this AssertPrecondition.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AssertPrecondition.


        :param id: The id of this AssertPrecondition.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def operator(self):
        """Gets the operator of this AssertPrecondition.  # noqa: E501


        :return: The operator of this AssertPrecondition.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this AssertPrecondition.


        :param operator: The operator of this AssertPrecondition.  # noqa: E501
        :type: str
        """
        if operator is None:
            raise ValueError("Invalid value for `operator`, must not be `None`")  # noqa: E501

        self._operator = operator

    @property
    def _property(self):
        """Gets the _property of this AssertPrecondition.  # noqa: E501


        :return: The _property of this AssertPrecondition.  # noqa: E501
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """Sets the _property of this AssertPrecondition.


        :param _property: The _property of this AssertPrecondition.  # noqa: E501
        :type: str
        """
        if _property is None:
            raise ValueError("Invalid value for `_property`, must not be `None`")  # noqa: E501

        self.__property = _property

    @property
    def updated(self):
        """Gets the updated of this AssertPrecondition.  # noqa: E501


        :return: The updated of this AssertPrecondition.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this AssertPrecondition.


        :param updated: The updated of this AssertPrecondition.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssertPrecondition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssertPrecondition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
