# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: v0.38.0
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComputeUnitUsage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'included': 'int',
        'used': 'int'
    }

    attribute_map = {
        'included': 'included',
        'used': 'used'
    }

    def __init__(self, included=None, used=None):  # noqa: E501
        """ComputeUnitUsage - a model defined in Swagger"""  # noqa: E501
        self._included = None
        self._used = None
        self.discriminator = None
        if included is not None:
            self.included = included
        if used is not None:
            self.used = used

    @property
    def included(self):
        """Gets the included of this ComputeUnitUsage.  # noqa: E501


        :return: The included of this ComputeUnitUsage.  # noqa: E501
        :rtype: int
        """
        return self._included

    @included.setter
    def included(self, included):
        """Sets the included of this ComputeUnitUsage.


        :param included: The included of this ComputeUnitUsage.  # noqa: E501
        :type: int
        """

        self._included = included

    @property
    def used(self):
        """Gets the used of this ComputeUnitUsage.  # noqa: E501


        :return: The used of this ComputeUnitUsage.  # noqa: E501
        :rtype: int
        """
        return self._used

    @used.setter
    def used(self, used):
        """Sets the used of this ComputeUnitUsage.


        :param used: The used of this ComputeUnitUsage.  # noqa: E501
        :type: int
        """

        self._used = used

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComputeUnitUsage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComputeUnitUsage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
