# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ContainerTopOKBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'processes': 'list[list[str]]',
        'titles': 'list[str]'
    }

    attribute_map = {
        'processes': 'Processes',
        'titles': 'Titles'
    }

    def __init__(self, processes=None, titles=None):  # noqa: E501
        """ContainerTopOKBody - a model defined in Swagger"""  # noqa: E501
        self._processes = None
        self._titles = None
        self.discriminator = None
        self.processes = processes
        self.titles = titles

    @property
    def processes(self):
        """Gets the processes of this ContainerTopOKBody.  # noqa: E501

        Each process running in the container, where each is process is an array of values corresponding to the titles.  # noqa: E501

        :return: The processes of this ContainerTopOKBody.  # noqa: E501
        :rtype: list[list[str]]
        """
        return self._processes

    @processes.setter
    def processes(self, processes):
        """Sets the processes of this ContainerTopOKBody.

        Each process running in the container, where each is process is an array of values corresponding to the titles.  # noqa: E501

        :param processes: The processes of this ContainerTopOKBody.  # noqa: E501
        :type: list[list[str]]
        """
        if processes is None:
            raise ValueError("Invalid value for `processes`, must not be `None`")  # noqa: E501

        self._processes = processes

    @property
    def titles(self):
        """Gets the titles of this ContainerTopOKBody.  # noqa: E501

        The ps column titles  # noqa: E501

        :return: The titles of this ContainerTopOKBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._titles

    @titles.setter
    def titles(self, titles):
        """Sets the titles of this ContainerTopOKBody.

        The ps column titles  # noqa: E501

        :param titles: The titles of this ContainerTopOKBody.  # noqa: E501
        :type: list[str]
        """
        if titles is None:
            raise ValueError("Invalid value for `titles`, must not be `None`")  # noqa: E501

        self._titles = titles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContainerTopOKBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContainerTopOKBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
