# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: v0.38.0
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Params(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'audio_feed': 'str',
        'browser': 'str',
        'location': 'str',
        'media_type': 'str',
        'network': 'str',
        'video_feed': 'str'
    }

    attribute_map = {
        'audio_feed': 'audio_feed',
        'browser': 'browser',
        'location': 'location',
        'media_type': 'media_type',
        'network': 'network',
        'video_feed': 'video_feed'
    }

    def __init__(self, audio_feed=None, browser=None, location=None, media_type=None, network=None, video_feed=None):  # noqa: E501
        """Params - a model defined in Swagger"""  # noqa: E501
        self._audio_feed = None
        self._browser = None
        self._location = None
        self._media_type = None
        self._network = None
        self._video_feed = None
        self.discriminator = None
        if audio_feed is not None:
            self.audio_feed = audio_feed
        self.browser = browser
        if location is not None:
            self.location = location
        if media_type is not None:
            self.media_type = media_type
        if network is not None:
            self.network = network
        if video_feed is not None:
            self.video_feed = video_feed

    @property
    def audio_feed(self):
        """Gets the audio_feed of this Params.  # noqa: E501


        :return: The audio_feed of this Params.  # noqa: E501
        :rtype: str
        """
        return self._audio_feed

    @audio_feed.setter
    def audio_feed(self, audio_feed):
        """Sets the audio_feed of this Params.


        :param audio_feed: The audio_feed of this Params.  # noqa: E501
        :type: str
        """

        self._audio_feed = audio_feed

    @property
    def browser(self):
        """Gets the browser of this Params.  # noqa: E501


        :return: The browser of this Params.  # noqa: E501
        :rtype: str
        """
        return self._browser

    @browser.setter
    def browser(self, browser):
        """Sets the browser of this Params.


        :param browser: The browser of this Params.  # noqa: E501
        :type: str
        """
        if browser is None:
            raise ValueError("Invalid value for `browser`, must not be `None`")  # noqa: E501

        self._browser = browser

    @property
    def location(self):
        """Gets the location of this Params.  # noqa: E501


        :return: The location of this Params.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Params.


        :param location: The location of this Params.  # noqa: E501
        :type: str
        """

        self._location = location

    @property
    def media_type(self):
        """Gets the media_type of this Params.  # noqa: E501


        :return: The media_type of this Params.  # noqa: E501
        :rtype: str
        """
        return self._media_type

    @media_type.setter
    def media_type(self, media_type):
        """Sets the media_type of this Params.


        :param media_type: The media_type of this Params.  # noqa: E501
        :type: str
        """

        self._media_type = media_type

    @property
    def network(self):
        """Gets the network of this Params.  # noqa: E501


        :return: The network of this Params.  # noqa: E501
        :rtype: str
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this Params.


        :param network: The network of this Params.  # noqa: E501
        :type: str
        """

        self._network = network

    @property
    def video_feed(self):
        """Gets the video_feed of this Params.  # noqa: E501


        :return: The video_feed of this Params.  # noqa: E501
        :rtype: str
        """
        return self._video_feed

    @video_feed.setter
    def video_feed(self, video_feed):
        """Sets the video_feed of this Params.


        :param video_feed: The video_feed of this Params.  # noqa: E501
        :type: str
        """

        self._video_feed = video_feed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Params, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Params):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
