# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PluginConfigUser(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gid': 'int',
        'uid': 'int'
    }

    attribute_map = {
        'gid': 'GID',
        'uid': 'UID'
    }

    def __init__(self, gid=None, uid=None):  # noqa: E501
        """PluginConfigUser - a model defined in Swagger"""  # noqa: E501
        self._gid = None
        self._uid = None
        self.discriminator = None
        if gid is not None:
            self.gid = gid
        if uid is not None:
            self.uid = uid

    @property
    def gid(self):
        """Gets the gid of this PluginConfigUser.  # noqa: E501

        g ID  # noqa: E501

        :return: The gid of this PluginConfigUser.  # noqa: E501
        :rtype: int
        """
        return self._gid

    @gid.setter
    def gid(self, gid):
        """Sets the gid of this PluginConfigUser.

        g ID  # noqa: E501

        :param gid: The gid of this PluginConfigUser.  # noqa: E501
        :type: int
        """

        self._gid = gid

    @property
    def uid(self):
        """Gets the uid of this PluginConfigUser.  # noqa: E501

        UID  # noqa: E501

        :return: The uid of this PluginConfigUser.  # noqa: E501
        :rtype: int
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this PluginConfigUser.

        UID  # noqa: E501

        :param uid: The uid of this PluginConfigUser.  # noqa: E501
        :type: int
        """

        self._uid = uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PluginConfigUser, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PluginConfigUser):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
