# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: {{ .Version }}
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class URLProxy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alias': 'str',
        'file_key': 'str'
    }

    attribute_map = {
        'alias': 'Alias',
        'file_key': 'FileKey'
    }

    def __init__(self, alias=None, file_key=None):  # noqa: E501
        """URLProxy - a model defined in Swagger"""  # noqa: E501
        self._alias = None
        self._file_key = None
        self.discriminator = None
        if alias is not None:
            self.alias = alias
        if file_key is not None:
            self.file_key = file_key

    @property
    def alias(self):
        """Gets the alias of this URLProxy.  # noqa: E501


        :return: The alias of this URLProxy.  # noqa: E501
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias):
        """Sets the alias of this URLProxy.


        :param alias: The alias of this URLProxy.  # noqa: E501
        :type: str
        """

        self._alias = alias

    @property
    def file_key(self):
        """Gets the file_key of this URLProxy.  # noqa: E501


        :return: The file_key of this URLProxy.  # noqa: E501
        :rtype: str
        """
        return self._file_key

    @file_key.setter
    def file_key(self, file_key):
        """Sets the file_key of this URLProxy.


        :param file_key: The file_key of this URLProxy.  # noqa: E501
        :type: str
        """

        self._file_key = file_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(URLProxy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, URLProxy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
