# coding: utf-8

"""
    Loadero Controller

    This application serves main Loadero's endpoints that can be used to manipulate test data and other services  # noqa: E501

    OpenAPI spec version: v0.38.0
    Contact: support@loadero.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ValidationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'int',
        'errors': 'dict(str, list[str])'
    }

    attribute_map = {
        'code': 'code',
        'errors': 'errors'
    }

    def __init__(self, code=None, errors=None):  # noqa: E501
        """ValidationResponse - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._errors = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if errors is not None:
            self.errors = errors

    @property
    def code(self):
        """Gets the code of this ValidationResponse.  # noqa: E501

        Status code of error  # noqa: E501

        :return: The code of this ValidationResponse.  # noqa: E501
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ValidationResponse.

        Status code of error  # noqa: E501

        :param code: The code of this ValidationResponse.  # noqa: E501
        :type: int
        """

        self._code = code

    @property
    def errors(self):
        """Gets the errors of this ValidationResponse.  # noqa: E501

        List of validation errors  # noqa: E501

        :return: The errors of this ValidationResponse.  # noqa: E501
        :rtype: dict(str, list[str])
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this ValidationResponse.

        List of validation errors  # noqa: E501

        :param errors: The errors of this ValidationResponse.  # noqa: E501
        :type: dict(str, list[str])
        """

        self._errors = errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ValidationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ValidationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
