name: bs

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'

  workflow_dispatch:

jobs:
  bs-job:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: echo
        run: echo "bs"
