name: CHECKS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: install-requirements
        run: pip install -r requirements.txt

      - name: lint
        run: ./check.sh lint

      - name: format
        run: ./check.sh format

      - name: test
        run: ./check.sh test unit

      - name: generate coverage report
        run: ./check.sh report

      - name: comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          pytest-coverage: pytest-coverage.txt
