name: LINT_AND_FORMAT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: lint
        uses: fylein/python-pylint-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc loadero-python

      - name: format
        uses: psf/black@stable
        with:
          options: "--check --verbose --config pyproject.toml"
          src: "./loadero-python"
