name: CHECKS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: install-requirements
        run: pip install -r requirements.txt

      - name: lint
        run: pylint --rcfile=.pylintrc loadero-python tests/*.py

      - name: format
        run: black --check --verbose --config pyproject.toml loadero_python tests

      - name: test
        run: pytest tests -vv
