name: PYPI-TEST

on:
  # push:
  #   branches: 
  #     - 'master'
  #   tags:
  #     - '*'
  # pull_request:
  #   branches: 
  #     - 'master'

  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: requirements/*.txt

      - name: install requirements
        run: |
          pip install -r requirements/test.txt
          pip install loadero-python

      - name: test
        run: |
          cd tests/integration
          export $(grep -v '^#' ../../.env | xargs)
          pytest -v
